[tool.poetry]
name = "satni_backend"
version = "1.2.5"
description = "Backend for sátni.org"
authors = ["Børre Gaup <albbas@gmail.com>"]
license = "GPLv3+"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
termwikitools = {git = "https://github.com/divvun/TermWikiTools"}
django = "^5.2.6"
django-environ = "^0.12.0"
mongoengine = "^0.29.1"
django-extensions = "^4.1"
django-cors-headers = "^4.9.0"
graphene-django = "^3.2.3"
graphene-mongo = "^0.4.4"

[tool.poetry.dev-dependencies]
nose2 = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
